image: Visual Studio 2017

branches:
  except:
  - maintenance/1.x

environment:
  SHFBROOT:  C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\
  SandCastleZipFile: SHFBInstaller.zip
  SandCastleUri: https://github.com/EWSoftware/SHFB/releases/download/v2017.1.28.0/SHFBInstaller_v20171.28.0.zip
  
install:
  - ps: Start-FileDownload $env:SandCastleUri -FileName $env:SandCastleZipFile
  - cmd: 7z x SHFBInstaller.zip -y
  - ps: msiexec /i InstallResources\SandcastleHelpFileBuilder.msi /quiet /qn /norestart /log install.log

configuration: Release

build_script:
  - ps: ./build.ps1 -Target Pack -Verbosity Diagnostic -configuration Release

test_script:
  - ps: ./build.ps1 -Target Test -Verbosity Verbose -configuration Release *> test.log

before_deploy:
  - cmd: msbuild Build\shfb\dotnetrdf.shfbproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=%CONFIGURATION% /p:HelpFileVersion=%GitVersion_NuGetVersion%

deploy:
  - provider: GitHub
    description: 'dotNetRDF $(GitVersion_SemVer)'
    auth_token:
      secure: j3GoyDavErTD91EcSTfNBbQyTc7tqpp+klmmz85xC4fjbE8Gl2brFjr8t3/Zzwmk
    on:
      appveyor_repo_tag: true 
    artifact: Build\shfb\Help.zip, Build\shfb\Help\dotNetRDFApi.chm, /.*\.nupkg/
  - provider: NuGet
    api_key:
      secure: xkVJcckbSBSStK7/jzgv6AUkI/QS1oeJNx6KUcHxoI9XrHI/m7VjFAslEGm9VEOo
    on:
      appveyor_repo_tag: true 
    artifact: /((?!Spin).)*.nupkg/

artifacts:
  - path: 'nugets\*.nupkg'
  - path: 'Build\shfb\Help\dotNetRDFApi.chm'
  - path: 'Build\shfb\Help'

on_finish:
  - ps: Push-AppveyorArtifact 'test.log'
